<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('nationalities')->insert([

            [
                'name' => 'Afegão',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sul-Africano',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Albanês',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Alemão',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Andorrano',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Angolano',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Antiguano',
                'continent' => 'América do Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Saudita',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Argelino',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Argentino',
                'continent' => 'América do Sul',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Arménio',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Australiano',
                'continent' => 'Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Austríaco',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Azerbaijano',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bahamense',
                'continent' => 'América do Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bangladês',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Barbadense',
                'continent' => 'América do Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bareinita',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Belga',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Belizenho',
                'continent' => 'América do Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Beninense',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Butanês',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bielorrusso',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Birmanês',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Boliviano',
                'continent' => 'América do Sul',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bosníaco',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Botsuanense',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Brasileiro',
                'continent' => 'América do Sul',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bruneíno',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Búlgaro',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Burquinense',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Burundiano',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cambojano',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Camarônes',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Canadense',
                'continent' => 'América do Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cabo-Verdiano',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chadiano',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chileno',
                'continent' => 'América do Sul',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chinês',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Colombiano',
                'continent' => 'América do Sul',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Comorense',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Congolês (Rep. Democrática)',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Congolês (República do Congo)',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Costarriquenho',
                'continent' => 'América do Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Croata',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cubano',
                'continent' => 'América do Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dinamarquês',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Djibutiano',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dominicano',
                'continent' => 'América do Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Egípcio',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Salvadorenho',
                'continent' => 'América do Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Emiradense',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Equatoriano',
                'continent' => 'América do Sul',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eritreu',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eslovaco',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Esloveno',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Espanhol',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Estoniano',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Etíope',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fijiano',
                'continent' => 'Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Filipino',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Finlandês',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Francês',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gabãoense',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gambiano',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ganense',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Georgiano',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Granadino',
                'continent' => 'América do Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Grego',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guatemalteco',
                'continent' => 'América do Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guianense',
                'continent' => 'América do Sul',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guineense',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guineense Equatorial',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Haitiano',
                'continent' => 'América do Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Holandês',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hondurenho',
                'continent' => 'América do Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Húngaro',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Iemenita',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Indiano',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Indonésio',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Iraquiano',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Iraniano',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Irlandês',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Islandês',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Israelita',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Italiano',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jamaicano',
                'continent' => 'América do Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Japonês',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jordaniano',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laosiano',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Letão',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Libanês',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Liberiano',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Líbio',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Liechtensteiniano',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lituano',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luxemburguês',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Macauense',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Macedônio',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Madagascarense',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Malaio',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Malaquenho',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maldivo',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maliano',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maltês',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Marroquino',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mauriciano',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mexicano',
                'continent' => 'América do Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Micronésio',
                'continent' => 'Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Moçambicano',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Moldavo',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Monegasco',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mongol',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Montenegrino',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Namibiano',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Neozelandês',
                'continent' => 'Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nepalês',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nicaraguense',
                'continent' => 'América do Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nigeriano',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Norueguês',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Omãnico',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paquistanês',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Panamenho',
                'continent' => 'América do Norte',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paraguaio',
                'continent' => 'América do Sul',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Peruano',
                'continent' => 'América do Sul',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Polonês',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Português',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Qatarense',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Romeno',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ruandês',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Russo',
                'continent' => 'Europa/Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sérvio',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Senegalês',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Singapurense',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sírio',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Somali',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sueco',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Suíço',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Surinamês',
                'continent' => 'América do Sul',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tailandês',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tanzaniano',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tcheco',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Timorense',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Togolês',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tunisiano',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Turco',
                'continent' => 'Europa/Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ucraniano',
                'continent' => 'Europa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ugandense',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Uruguaio',
                'continent' => 'América do Sul',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Uzbeque',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Venezuelano',
                'continent' => 'América do Sul',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vietnamita',
                'continent' => 'Ásia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zambiano',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zimbabuense',
                'continent' => 'África',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
